version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: final_prj_class_image
    container_name: final_project
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    environment:
       FLASK_DEBUG: "1"
